config/routes.rb
Rails.application.routes.draw do
  resources :patients do
    resources :logs, only: :create
  end
  resources :reservations, except: :show
  root to: "reservations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  validates :text, presence: true
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :kana
    validates :phone
    validates :email
  end
  
  has_many :logs, dependent: :delete_all
  has_many :reservations, dependent: :destroy

  enum sex: {
    男:1,
    女:2
  }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  with_options presence: true do
    validates :date
  end

  belongs_to :patient
  belongs_to :schedule

  def rsv_date_check(days)
    none = ""
    if self.date == Date.today + days
      return self.patient.name
    else
      return none
    end
  end

  def rsv_time_check(schedule_id)
    if self.schedule_id == schedule_id
      return self.patient.name
    else
      return nil
    end
  end
  
  def self.rsv_time_sort(schedules)
    sorted_ary = []
    schedules.times do |i|
      sorted_ary << Reservation.where(schedule_id: i + 1,
                                      date: Date.today..Date.today + 13)
    end
    return sorted_ary
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :time, presence: true
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_today_rsv
  
  private
  def set_today_rsv
    @schedules    = Schedule.all
    @today_rsv    = Reservation.where(date: Date.today)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def create
    @log = Log.create(log_params)
    if @log.save
      redirect_to patient_path(params[:patient_id])
    end
  end

  private
  def log_params
    params.require(:log).permit(:text).merge(patient_id: params[:patient_id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
    @logs    = @patient.logs.includes(:patient)
    @log     = Log.new
    @rsvs    = Reservation.where(patient_id: params[:id])
                          .where('date >= ?', Date.today)
                          .order(:date)
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    patient = Patient.find(params[:id])
    patient.update(patient_params)
    redirect_to patient_path(params[:id])
  end

  def destroy
    patient = Patient.find(params[:id])
    patient.destroy
    redirect_to reservations_path
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :kana, :phone, :email)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.rsv_time_sort(@schedules.length)
  end

  def new
    @reservation = Reservation.new
    @schedules   = Schedule.all
    @patients    = Patient.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to reservations_path
    else
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @schedules   = Schedule.all
    @patients    = Patient.all
  end

  def update
    reservation = Reservation.find(params[:id])
    reservation.update(reservation_params)
    # redirect_to patient_path(reservation_params[:patient_id])
    redirect_to reservations_path

  end

  def destroy
    rsv = Reservation.find(params[:id])
    rsv.destroy
    redirect_to reservations_path
  end

  private
  def reservation_params
    params.require(:reservation).permit(:"date(1i)",
                                        :"date(2i)",
                                        :"date(3i)",
                                        :schedule_id,
                                        :patient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_header.html.haml
.header_container
  .header_container__links
    .link
      = link_to reservations_path do
        予約一覧
    .link
      = link_to new_reservation_path do
        予約登録
    .link
      = link_to patients_path do
        患者一覧
    .link
      = link_to new_patient_path do
        患者登録

app/views/layouts/_side.html.haml
.side_container
  .side_container__top
    .side_container__top__title
      %h1 Medi-Chart(beta)
  .side_container__bottom
    .side_container__bottom__content
      %table
        .table_header
          = Date.today.strftime("%y/%m/%d (%a)")
        - @schedules.each_with_index do |schedule, i|
          %tr
            %td.table_data
              = schedule.time
            %td
              - @today_rsv.each do |r|
                = link_to patient_path(r.patient_id) do
                  = r.rsv_time_check(schedule.id)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MediChart
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/side'
    = render 'layouts/header'
    = yield

app/views/patients/edit.html.haml
.main_container
  .main_container__top
    %p 患者情報修正
  .main_container__bottom
    .main_container__bottom__content
      = form_for @patient do |f|
        = f.text_field :name, placeholder: "名前(必須)"
        = f.text_field :kana, placeholder: "よみ(必須)"
        = f.text_field :phone, placeholder: "電話(必須)"
        = f.text_field :email, placeholder: "email(必須)"
        = f.date_select :birthday, start_year:1930, use_month_numbers: true
        = f.text_field :age, placeholder: "年齢"
        = f.select :sex, Patient.sexes.keys, {prompt: "性別"}
        = f.text_field :zip, placeholder: "郵便番号"
        = f.text_field :address1, placeholder: "住所（市区町村まで）"
        = f.text_field :address2, placeholder: "住所（番地・建物等）"
        = f.submit "登録する"

app/views/patients/index.html.haml
.main_container
  .main_container__top
    -# %patient 患者一覧
  .main_container__bottom
    .main_container__bottom__content
      %table
        %tr.table_row
          %th.th_wide  名前
          %th.th_wide  読み
          %th.th_narrow  誕生日
          %th.th_narrow  年齢
          %th.th_narrow  性別
          %th.th_normal  郵便番号
          %th.th_normal  住所1
          %th.th_normal  住所2
          %th.th_wide    email
          %th.th_narrow  電話番号
        - @patients.each do |patient|
          %tr
            %td
              = link_to patient_path(patient.id) do
                = patient.name
            %td
              = patient.kana
            %td
              = patient.birthday
            %td
              = patient.age
            %td
              = patient.sex
            %td
              = patient.zip
            %td
              = patient.address1
            %td
              = patient.address2
            %td
              = patient.email
            %td
              = patient.phone

app/views/patients/new.html.haml
.main_container
  .main_container__top
    %p 患者登録
  .main_container__bottom
    .main_container__bottom__content
      = form_for @patient do |f|
        = f.text_field :name, placeholder: "名前(必須)"
        = f.text_field :kana, placeholder: "よみ(必須)"
        = f.text_field :phone, placeholder: "電話(必須)"
        = f.text_field :email, placeholder: "email(必須)"
        = f.date_select :birthday, start_year:1930, use_month_numbers: true
        = f.text_field :age, placeholder: "年齢"
        = f.select :sex, Patient.sexes.keys, {prompt: "性別"}
        = f.text_field :zip, placeholder: "郵便番号"
        = f.text_field :address1, placeholder: "住所（市区町村まで）"
        = f.text_field :address2, placeholder: "住所（番地・建物等）"
        = f.submit "登録する"

app/views/patients/show.html.haml
.main_container
  .main_container__top
    %p 患者詳細
  .main_container__bottom
    .main_container__bottom__content
      %table
        %tr.table_row
          %th.th_normal  名前
          %th.th_normal  読み
          %th.th_narrow  誕生日
          %th.th_narrow  年齢
          %th.th_narrow  性別
          %th.th_normal  郵便番号
          %th.th_normal  住所1
          %th.th_normal  住所2
          %th.th_wide    email
          %th.th_narrow  電話番号
        %tr
          %td
            = @patient.name
          %td
            = @patient.kana
          %td
            = @patient.birthday
          %td
            = @patient.age
          %td
            = @patient.sex
          %td
            = @patient.zip
          %td
            = @patient.address1
          %td
            = @patient.address2
          %td
            = @patient.email
          %td.table_data
            = @patient.phone
          %td
            = link_to "[修正]", "/patients/#{@patient.id}/edit"
          %td
            = link_to "[削除]", "/patients/#{@patient.id}", method: :delete
    .main_container__bottom__content
      = "#{@patient.name}さんの今後の予約"
      - @rsvs.each do |rsv|
        .main_container__bottom__content--next_rsv
          = "#{rsv.date} #{rsv.schedule.time}"
          = link_to "[編集]", "/reservations/#{rsv.id}/edit"
          = link_to "[削除]", "/reservations/#{rsv.id}", method: :delete
    .main_container__bottom__content
      = form_for @log, url: patient_logs_path(@patient.id) do |f|
        = f.text_field :text, placeholder: "記録"
        = f.submit "送信"
      - @logs.each do |log|
        .text
          = log.created_at.strftime('%y/%m/%d')
          = log.text

app/views/reservations/edit.html.haml
.main_container
  .main_container__top
    %p 予約変更
  .main_container__bottom
    .main_container__bottom__content
    = form_for @reservation do |r|
      = r.date_select :date, {placeholder: "日付を選択してください"}
      = r.select :schedule_id, @schedules.map{ |schedule| [schedule.time, schedule.id] }
      = r.select :patient_id, @patients.map{ |patient| [patient.name, patient.id] }
      = r.submit "変更する"

app/views/reservations/index.html.haml
.main_container
  .main_container__top
    -# %p 予約一覧
  .main_container__bottom
    .main_container__bottom__content
      %table
        %tr.table_row
          %th.table_header#table_header_week
          - for i in 0..13 do
            %th.table_header#table_header_week
              = (Date.today + i).strftime("%m/%d(%a)")
        %tr#spacer
        - @schedules.each_with_index do |schedule, i|
          %tr
            %td.table_data
              = schedule.time
            - if @reservations[i].present?
              - 14.times do |days|
                %td
                  - @reservations[i].each do |r|
                    = link_to patient_path(r.patient_id) do
                      = r.rsv_date_check(days)

app/views/reservations/new.html.haml
.main_container
  .main_container__top
    %p 予約登録
  .main_container__bottom
    .main_container__bottom__content
    = form_for @reservation do |r|
      = r.date_select :date, use_month_numbers: true, placeholder: "日付を選択してください"
      = r.select :schedule_id, @schedules.map{ |schedule| [schedule.time, schedule.id] }
      = r.select :patient_id, @patients.map{ |patient| [patient.name, patient.id] }
      = r.submit "登録する"